/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

import co.unicauca.workflow.domain.entities.FormatoA;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class Observaciones extends javax.swing.JPanel {

    /**
     * Creates new form Observaciones
     */
    public Observaciones() {
        initComponents();
    }
public void setFormatoA(FormatoA formato) {
    lblUTitulo.setText(formato.getTitle());
    lblUEstudiante.setText(formato.getStudentCode()); // O nombre si tienes
    lblUDirector.setText(formato.getProyectManager());
    lblUModalidad.setText(formato.getMode()); // Aquí puse el modo como "programa"
    lblPDF.setText(formato.getArchivoPDF() != null ? formato.getArchivoPDF() : "Sin PDF");

    // Estado
    CBXAprovado.setSelected("Aprobado".equalsIgnoreCase(formato.getEstado()));
    CBXRechazado.setSelected("Rechazado".equalsIgnoreCase(formato.getEstado()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblUTitulo = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblUEstudiante = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        lblDirector = new javax.swing.JLabel();
        lblUDirector = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lblModalidad = new javax.swing.JLabel();
        lblUModalidad = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblPDF = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        CBXAprovado = new javax.swing.JCheckBox();
        CBXRechazado = new javax.swing.JCheckBox();
        txtObservaciones = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(533, 371));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Titulo");

        lblUTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblUTitulo.setText("Titulo");

        lblEstudiante.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblEstudiante.setForeground(new java.awt.Color(0, 0, 0));
        lblEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstudiante.setText("Estudiante");

        lblUEstudiante.setForeground(new java.awt.Color(51, 51, 51));
        lblUEstudiante.setText("Estudiante");

        lblDirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblDirector.setForeground(new java.awt.Color(0, 0, 0));
        lblDirector.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDirector.setText("Dir.Proyecto");

        lblUDirector.setForeground(new java.awt.Color(51, 51, 51));
        lblUDirector.setText("Director");

        lblModalidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblModalidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblModalidad.setText("Modalidad");

        lblUModalidad.setForeground(new java.awt.Color(51, 51, 51));
        lblUModalidad.setText("Modalidad");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblPDF.setForeground(new java.awt.Color(102, 102, 255));
        lblPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPDF.setText("RUTA PDF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        lblObservaciones.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservaciones.setText("Observaciones");

        CBXAprovado.setText("Aprovado");

        CBXRechazado.setText("Rechazado");

        txtObservaciones.setBackground(new java.awt.Color(255, 255, 255));
        txtObservaciones.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(153, 153, 153));
        txtObservaciones.setText("   Ingrese sus Observaciones");
        txtObservaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtObservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObservacionesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addComponent(lblDirector, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContenidoLayout.createSequentialGroup()
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModalidad, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(CBXAprovado)
                        .addGap(106, 106, 106)
                        .addComponent(CBXRechazado))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblUTitulo))
                .addGap(3, 3, 3)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante)
                    .addComponent(lblUEstudiante))
                .addGap(3, 3, 3)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirector)
                    .addComponent(lblUDirector))
                .addGap(3, 3, 3)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModalidad)
                    .addComponent(lblUModalidad))
                .addGap(3, 3, 3)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(lblObservaciones)
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(txtObservaciones))
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBXAprovado)
                    .addComponent(CBXRechazado))
                .addGap(53, 53, 53))
        );

        add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 533, 371));
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObservacionesMousePressed
     txtObservaciones.getText().equals("   Ingrese sus Observaciones");
        txtObservaciones.setText("");
       txtObservaciones.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtObservacionesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBXAprovado;
    private javax.swing.JCheckBox CBXRechazado;
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblPDF;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUDirector;
    private javax.swing.JLabel lblUEstudiante;
    private javax.swing.JLabel lblUModalidad;
    private javax.swing.JLabel lblUTitulo;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
