/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.workflow.presentation.views;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class SubirFormatoA extends javax.swing.JPanel {

    /**
     * Creates new form Princi
     */
    public SubirFormatoA() {
        initComponents();
        initStyles();
    }
private void initStyles(){
      FlatMTMaterialLighterIJTheme.setup();
      
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        lbPDF = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lbTitulo = new javax.swing.JLabel();
        lbModalidad = new javax.swing.JLabel();
        txtModalidad = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        lbDirector = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        lbCodirector = new javax.swing.JLabel();
        txtCodirector = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        Fecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        lbObjGen = new javax.swing.JLabel();
        txtObGen = new javax.swing.JTextField();
        txtObjEspecifico = new javax.swing.JTextField();
        lbObEspecifico = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtRutaPDF = new javax.swing.JLabel();
        btPDF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(641, 498));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setPreferredSize(new java.awt.Dimension(641, 498));

        lbPDF.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbPDF.setForeground(new java.awt.Color(0, 0, 0));
        lbPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPDF.setText("PDF");

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(153, 153, 153));
        txtTitulo.setText("Ingrese el Titulo del Proyecto");
        txtTitulo.setBorder(null);
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTituloMousePressed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Titulo");

        lbModalidad.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lbModalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbModalidad.setText("Modalidad");

        txtModalidad.setBackground(new java.awt.Color(255, 255, 255));
        txtModalidad.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtModalidad.setForeground(new java.awt.Color(153, 153, 153));
        txtModalidad.setText("Ingrese la modalidad");
        txtModalidad.setBorder(null);
        txtModalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtModalidadMousePressed(evt);
            }
        });

        lbDirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbDirector.setForeground(new java.awt.Color(0, 0, 0));
        lbDirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDirector.setText("Director de proyecto");

        txtDirector.setBackground(new java.awt.Color(255, 255, 255));
        txtDirector.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtDirector.setForeground(new java.awt.Color(153, 153, 153));
        txtDirector.setText("Ingrese el Director del Proyecto");
        txtDirector.setBorder(null);
        txtDirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDirectorMousePressed(evt);
            }
        });

        lbCodirector.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbCodirector.setForeground(new java.awt.Color(0, 0, 0));
        lbCodirector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodirector.setText("Codirector de proyecto");

        txtCodirector.setBackground(new java.awt.Color(255, 255, 255));
        txtCodirector.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtCodirector.setForeground(new java.awt.Color(153, 153, 153));
        txtCodirector.setText("Ingrese el Codirector del Proyecto");
        txtCodirector.setBorder(null);
        txtCodirector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodirectorMousePressed(evt);
            }
        });

        Fecha.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("Fecha");

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(153, 153, 153));
        txtFecha.setText("Ingrese la Fecha");
        txtFecha.setBorder(null);
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaMousePressed(evt);
            }
        });

        lbObjGen.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbObjGen.setForeground(new java.awt.Color(0, 0, 0));
        lbObjGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbObjGen.setText("Objetivo General");

        txtObGen.setBackground(new java.awt.Color(255, 255, 255));
        txtObGen.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtObGen.setForeground(new java.awt.Color(153, 153, 153));
        txtObGen.setText("   Ingrese el Objetivo General");
        txtObGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtObGen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObGenMousePressed(evt);
            }
        });

        txtObjEspecifico.setBackground(new java.awt.Color(255, 255, 255));
        txtObjEspecifico.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        txtObjEspecifico.setForeground(new java.awt.Color(153, 153, 153));
        txtObjEspecifico.setText("   Ingrese los objetivos especificos");
        txtObjEspecifico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtObjEspecifico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtObjEspecificoMousePressed(evt);
            }
        });

        lbObEspecifico.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbObEspecifico.setForeground(new java.awt.Color(0, 0, 0));
        lbObEspecifico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbObEspecifico.setText("Objetivos Especificos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtRutaPDF.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtRutaPDF.setForeground(new java.awt.Color(51, 51, 255));
        txtRutaPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRutaPDF.setText("Ruta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txtRutaPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btPDF.setText("Adjunte un PDF");
        btPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPDFMousePressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(65, 55, 171));
        jButton1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBIR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(txtCodirector, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(txtDirector, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(txtModalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCodirector, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                                .addComponent(lbObjGen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtObjEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                    .addComponent(txtObGen)
                                    .addGroup(ContenidoLayout.createSequentialGroup()
                                        .addComponent(lbObEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(140, 140, 140))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(ContenidoLayout.createSequentialGroup()
                                                .addComponent(lbPDF)
                                                .addGap(47, 47, 47)
                                                .addComponent(btPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(8, 8, 8)))
                                .addGap(38, 38, 38))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(lbTitulo)
                                .addGap(13, 13, 13)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbModalidad))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(lbObjGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObGen)))
                        .addGap(13, 13, 13)
                        .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(txtModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDirector)
                                .addGap(13, 13, 13)
                                .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbCodirector)
                                .addGap(13, 13, 13)
                                .addComponent(txtCodirector, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(Fecha)
                                .addGap(15, 15, 15)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContenidoLayout.createSequentialGroup()
                                .addComponent(lbObEspecifico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtObjEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btPDF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMousePressed
        manejarPlaceHolder(txtTitulo, "Ingrese el Titulo del Proyecto", 
                        txtModalidad, txtDirector, txtCodirector, txtFecha, txtObGen, txtObjEspecifico);
    }//GEN-LAST:event_txtTituloMousePressed

    private void txtModalidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModalidadMousePressed
        manejarPlaceHolder(txtModalidad, "Ingrese la modalidad", 
                        txtTitulo, txtDirector, txtCodirector, txtFecha, txtObGen, txtObjEspecifico);
    }//GEN-LAST:event_txtModalidadMousePressed

    private void txtDirectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDirectorMousePressed
        manejarPlaceHolder(txtDirector, "Ingrese el Director del Proyecto", 
                        txtModalidad, txtTitulo, txtCodirector, txtFecha, txtObGen, txtObjEspecifico);
    }//GEN-LAST:event_txtDirectorMousePressed

    private void txtCodirectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodirectorMousePressed
       manejarPlaceHolder(txtCodirector, "Ingrese el Codirector del Proyecto", 
                        txtModalidad, txtDirector, txtTitulo, txtFecha, txtObGen, txtObjEspecifico);
    }//GEN-LAST:event_txtCodirectorMousePressed

    private void txtFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMousePressed
        manejarPlaceHolder(txtFecha, "Ingrese la Fecha", 
                        txtModalidad, txtDirector, txtCodirector, txtTitulo, txtObGen, txtObjEspecifico);
    }//GEN-LAST:event_txtFechaMousePressed

    private void txtObGenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObGenMousePressed
       manejarPlaceHolder(txtObGen, "   Ingrese el Objetivo General", 
                        txtModalidad, txtDirector, txtCodirector, txtFecha, txtTitulo, txtObjEspecifico);
    }//GEN-LAST:event_txtObGenMousePressed

    private void txtObjEspecificoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtObjEspecificoMousePressed
       manejarPlaceHolder(txtObjEspecifico, "   Ingrese los objetivos especificos", 
                       txtModalidad, txtDirector, txtCodirector, txtFecha, txtObGen, txtTitulo);
    }//GEN-LAST:event_txtObjEspecificoMousePressed

    private void btPDFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPDFMousePressed
      JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Seleccionar archivo PDF");

    // Filtro para solo mostrar PDFs
    FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos PDF", "pdf");
    fileChooser.setFileFilter(filtro);

    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivoSeleccionado = fileChooser.getSelectedFile();
        
        try {
            // Ruta de destino dentro del proyecto
            String carpetaDestino = System.getProperty("user.dir") + File.separator + "archivosPDF";
            File directorio = new File(carpetaDestino);
            if (!directorio.exists()) {
                directorio.mkdir(); // crea la carpeta si no existe
            }

            // Copiar el archivo al destino
            File archivoDestino = new File(carpetaDestino, archivoSeleccionado.getName());
            Files.copy(archivoSeleccionado.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);

            // Guardar la ruta en un atributo (para luego insertarla en la BD)
            String rutaGuardada = archivoDestino.getAbsolutePath();
            txtRutaPDF.setText(rutaGuardada); // puedes mostrarlo en un JTextField

            JOptionPane.showMessageDialog(this, "Archivo guardado en: " + rutaGuardada);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btPDFMousePressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

 private void manejarPlaceHolder(JTextField campo, String placeholder, JTextField... otros) {
    // Si hago clic en este campo y está en modo placeholder → lo limpio
    if (campo.getText().equals(placeholder)) {
        campo.setText("");
        campo.setForeground(Color.BLACK);
    }

    // Si los otros campos están vacíos → les devuelvo su placeholder
    for (JTextField otro : otros) {
        if (otro.getText().isEmpty()) {
             if (otro == txtTitulo) {
                otro.setText("Ingrese el Titulo del Proyecto");
            } else if (otro == txtModalidad) {
                otro.setText("Ingrese la modalidad");
            } else if (otro == txtDirector) {
                otro.setText("Ingrese el Director del Proyecto");
            } else if (otro == txtCodirector) {
                otro.setText("Ingrese el Codirector del Proyecto");
            } else if (otro == txtFecha) {
                otro.setText("   Ingrese la Fecha del Proyecto");
            } else if (otro == txtObGen) {
                otro.setText("Ingrese el Objetivo General");
            } else if (otro == txtObjEspecifico) {
                otro.setText("   Ingrese los objetivos especificos");
            }
            otro.setForeground(Color.GRAY);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton btPDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbCodirector;
    private javax.swing.JLabel lbDirector;
    private javax.swing.JLabel lbModalidad;
    private javax.swing.JLabel lbObEspecifico;
    private javax.swing.JLabel lbObjGen;
    private javax.swing.JLabel lbPDF;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtCodirector;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtModalidad;
    private javax.swing.JTextField txtObGen;
    private javax.swing.JTextField txtObjEspecifico;
    private javax.swing.JLabel txtRutaPDF;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
