
package co.unicauca.workflow.presentation;
import java.awt.Color;
import javax.swing.JOptionPane;
import co.unicauca.workflow.domain.service.UserService;
import co.unicauca.workflow.access.IUserRepository;
import co.unicauca.workflow.access.UserRepository;

public class GUILogin extends javax.swing.JFrame {

    private final UserService userService;
    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
            IUserRepository repo = new UserRepository();
        userService = new UserService(repo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Unicauca = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        sepEmail = new javax.swing.JSeparator();
        lbContrasenia = new javax.swing.JLabel();
        sepContrasenia = new javax.swing.JSeparator();
        tfContrasenia = new javax.swing.JPasswordField();
        pnlBttLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblMensaje2 = new javax.swing.JLabel();
        pnlBttRegistrarse = new javax.swing.JPanel();
        lblRegistrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Unicauca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/unicauca-02.png"))); // NOI18N
        Unicauca.setText("jLabel1");
        BackGround.add(Unicauca, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 340, 510));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/unicauca/workflow/presentation/images/Logo.png"))); // NOI18N
        Logo.setText("jLabel1");
        BackGround.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 110));

        lbTitulo.setFont(new java.awt.Font("Roboto SemiBold", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbTitulo.setText("INICIAR SESION");
        BackGround.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 320, 60));

        lbEmail.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("Email");
        BackGround.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 30));

        tfEmail.setBackground(new java.awt.Color(255, 255, 255));
        tfEmail.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(204, 204, 204));
        tfEmail.setText("Ingrese su email");
        tfEmail.setBorder(null);
        tfEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfEmailMousePressed(evt);
            }
        });
        BackGround.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 470, 30));

        sepEmail.setBackground(new java.awt.Color(255, 255, 255));
        sepEmail.setForeground(new java.awt.Color(0, 0, 0));
        sepEmail.setOpaque(true);
        BackGround.add(sepEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 420, 20));

        lbContrasenia.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbContrasenia.setForeground(new java.awt.Color(51, 51, 51));
        lbContrasenia.setText("Contraseña");
        BackGround.add(lbContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 170, 30));

        sepContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        sepContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        sepContrasenia.setOpaque(true);
        BackGround.add(sepContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 420, 20));

        tfContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        tfContrasenia.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        tfContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        tfContrasenia.setText("**********");
        tfContrasenia.setBorder(null);
        tfContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfContraseniaMousePressed(evt);
            }
        });
        BackGround.add(tfContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 420, 20));

        pnlBttLogin.setBackground(new java.awt.Color(0, 102, 204));
        pnlBttLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBttLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBttLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBttLoginMouseExited(evt);
            }
        });

        lblLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblLogin.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("ENTRAR");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlBttLoginLayout = new javax.swing.GroupLayout(pnlBttLogin);
        pnlBttLogin.setLayout(pnlBttLoginLayout);
        pnlBttLoginLayout.setHorizontalGroup(
            pnlBttLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBttLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBttLoginLayout.setVerticalGroup(
            pnlBttLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBttLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BackGround.add(pnlBttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 170, 40));

        lblMensaje.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 102, 102));
        lblMensaje.setText(" ");
        BackGround.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 250, 40));

        lblMensaje2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblMensaje2.setForeground(new java.awt.Color(0, 102, 204));
        lblMensaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje2.setText("¿No tienes usuario?");
        BackGround.add(lblMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 200, -1));

        pnlBttRegistrarse.setBackground(new java.awt.Color(0, 102, 204));
        pnlBttRegistrarse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRegistrarse.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrarse.setText("REGISTRARSE");
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBttRegistrarseLayout = new javax.swing.GroupLayout(pnlBttRegistrarse);
        pnlBttRegistrarse.setLayout(pnlBttRegistrarseLayout);
        pnlBttRegistrarseLayout.setHorizontalGroup(
            pnlBttRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        pnlBttRegistrarseLayout.setVerticalGroup(
            pnlBttRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        BackGround.add(pnlBttRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 200, 40));
        pnlBttRegistrarse.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmailMousePressed
      if( tfEmail.getText().equals("Ingrese su email")){
       tfEmail.setText("");
       tfEmail.setForeground(Color.BLACK);
      }
      if(String.valueOf(tfContrasenia.getPassword()).isEmpty()){
       tfContrasenia.setText("**********");
       tfContrasenia.setForeground(Color.GRAY);
      }
    }//GEN-LAST:event_tfEmailMousePressed

    private void tfContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfContraseniaMousePressed
        if(String.valueOf(tfContrasenia.getPassword()).equals("**********")){
        tfContrasenia.setText("");
        tfContrasenia.setForeground(Color.BLACK);
        }
        if(tfEmail.getText().isEmpty()){
        tfEmail.setText("Ingrese su email");
        tfEmail.setForeground(Color.GRAY);}
    }//GEN-LAST:event_tfContraseniaMousePressed

    private void pnlBttLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBttLoginMouseExited
        pnlBttLogin.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_pnlBttLoginMouseExited

    private void pnlBttLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBttLoginMouseEntered
        pnlBttLogin.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_pnlBttLoginMouseEntered

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
          String usuario = tfEmail.getText().trim();
    String clave = String.valueOf(tfContrasenia.getPassword()).trim();

    // Validar campos vacíos
    boolean faltaUsuario = (usuario == null || usuario.isEmpty() || usuario.equals("Ingrese su email"));
    boolean faltaClave = (clave == null || clave.isEmpty() || clave.equals("**********"));

    if (faltaUsuario && faltaClave) {
        lblMensaje.setText("Por favor completa todos los campos.");
        return;
    }

    if (faltaUsuario) {
        JOptionPane.showMessageDialog(this,
            "Debes ingresar un email.",
            "Campo vacío",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (faltaClave) {
        JOptionPane.showMessageDialog(this,
            "Debes ingresar una contraseña.",
            "Campo vacío",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Aquí conectamos con UserService
        //co.unicauca.workflow.domain.services.UserService userService = new co.unicauca.workflow.domain.services.UserService();
boolean autenticado = userService.authenticateUser(usuario, clave);


        if (autenticado) {
            JOptionPane.showMessageDialog(this,
                "¡Bienvenido, " + usuario + "!",
                "Inicio de sesión exitoso",
                JOptionPane.INFORMATION_MESSAGE);

            // Aquí podrías abrir la siguiente ventana del sistema
            // Ejemplo:
            // GUIPrincipal ventana = new GUIPrincipal();
            // ventana.setVisible(true);
            // this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "Usuario o contraseña incorrectos.",
                "Error de autenticación",
                JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Ocurrió un error al intentar autenticar: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_lblLoginMouseClicked

    
    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        pnlBttLogin.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseEntered
          pnlBttRegistrarse.setBackground(new Color(0,64,128));
    }//GEN-LAST:event_lblRegistrarseMouseEntered

    private void lblRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseExited
        pnlBttRegistrarse.setBackground(new Color(0,102,204));
    }//GEN-LAST:event_lblRegistrarseMouseExited

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        GUISingIn ventanaSingIn = new GUISingIn(); // crear la nueva ventana
        ventanaSingIn.setVisible(true);            // mostrarla
        this.dispose();       
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Unicauca;
    private javax.swing.JLabel lbContrasenia;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMensaje2;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JPanel pnlBttLogin;
    private javax.swing.JPanel pnlBttRegistrarse;
    private javax.swing.JSeparator sepContrasenia;
    private javax.swing.JSeparator sepEmail;
    private javax.swing.JPasswordField tfContrasenia;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables
}
